[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags =
    -D USB_MIDI_AUDIO_SERIAL
    -D TEENSY_OPT_FASTER_LTO
    -O2
lib_deps =
    paulstoffregen/ILI9341_t3
    paulstoffregen/XPT2046_Touchscreen
    thomasfredericks/Bounce2
lib_ldf_mode = deep+
monitor_speed = 115200
