#pragma once
#include <Arduino.h>

#define MAX_VOICES 16
#define NUM_VOICES 8
#define SAMPLE_RATE 44100.0f
#define BLOCK_SIZE 128

enum ParamId : uint8_t {
    P_VCO1_WAVE, P_VCO1_OCT, P_VCO1_PITCH, P_VCO1_SHAPE,
    P_VCO2_WAVE, P_VCO2_OCT, P_VCO2_PITCH, P_VCO2_SHAPE,
    P_VCO2_CROSS_MOD, P_VCO2_SYNC, P_VCO2_RING,
    P_MIX_VCO1, P_MIX_VCO2, P_MIX_MULTI,
    P_FILT_CUTOFF, P_FILT_RESO, P_FILT_DRIVE, P_FILT_KEYTRK, P_FILT_TYPE,
    P_AEG_A, P_AEG_D, P_AEG_S, P_AEG_R,
    P_MEG_A, P_MEG_D, P_MEG_S, P_MEG_R, P_MEG_DEST, P_MEG_AMT,
    P_LFO_WAVE, P_LFO_RATE, P_LFO_DEPTH, P_LFO_DEST,
    P_FX_MOD_TYPE, P_FX_MOD_DEPTH,
    P_FX_DELAY_TIME, P_FX_DELAY_FB, P_FX_DELAY_MIX,
    P_FX_REVERB_SIZE, P_FX_REVERB_MIX,
    P_MASTER_VOL, P_PORTAMENTO, P_VOICE_MODE,
    PARAM_COUNT
};

enum LFODest : uint8_t {
    LFO_DEST_PITCH = 0,
    LFO_DEST_SHAPE,
    LFO_DEST_CUTOFF,
    LFO_DEST_AMP,
    LFO_DEST_COUNT
};

struct Patch {
    float params[PARAM_COUNT];
    char name[17];
};
